language: android
jdk:
  - oraclejdk8
android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-25.0.1
    - android-25
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-25
    - sys-img-armeabi-v7a-android-15
licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
script:
  - ./gradlew build